### ISSUE TITLE
Add config and functions for source_value and source_concept_id

### ISSUE THREAD

**Issue by croeder** [cladteam/CCDA_OMOP_by_Python#60]
this will impact #39 creating the vocab tables
We need more than just the concept_id and domain_id that come out of concept_relationship and concept tables at the end, the concept_id_2 side,  but the concept_code and concept_id  on the concept_id_1 side of concept relationship.

**Comment by AdamLeeIT** [comment]
I 'think' this is resolved, but should reassign to @tannerzhang ??

**Comment by chrisroederucdenver** [comment]
It is not resolved. It's not about vocabulary (note the tag Structural Mapping), but mappings for those fields in the metadata for the domain tables. <domain>_source_value is trivial, <domain>_source_concept_id requires a field in the table we get back from JHU.

For example for the measurement table, it looks like source_value is there, but source_concept_id is None as a place holder.

`        'measurement_source_value': {
            'config_type': 'FIELD',
            'element': "hl7:code" ,
            'attribute': "code",
            'order':  17
        },

        'measurement_source_concept_id':    { 'config_type': None, 'order':  18 },`

**Comment by chrisroederucdenver** [comment]
there's an concat functoin for putting the vocab and code together for source value. These have been used.

**Comment by angelelli** [comment]
@chrisroederucdenver  I see that you recently added this to the project. Should it be re-opened? Is this a requirement that will go with the #467 Implement a unified mapping table?

**Comment by chrisroederucdenver** [comment]
@angelelli  No, I'm reading tickets to fast and dreaming they mean what I wnant them to mean. 
Maybe there's another one that has this dreamt-up meanding.

What I was thinking of is actually putting in or making sure  the source_value and source_concept_id fields are populated.
